# Generated by Django 5.2.8 on 2025-12-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
