# Generated by Django 5.2.8 on 2026-01-01 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 7, 52, 9, 144734, tzinfo=datetime.timezone.utc)),
        ),
    ]
